---
hostname: iptables-firewall
ip_manage: localhost
ssh_port: 22
username: prototipo
password: prototipo
device_type: linux


INTERFACES:
    - name: eth0
      addr: 192.168.1.1/24
      description: InterfaceInterna
    - name: eth1
      addr: 200.19.0.1/24
      description: InterfaceExterna
