---
hostname: iptables-firewall
ip_manage: 10.12.0.121
ssh_port: 22
username: iptables
password: iptables
device_type: linux


INTERFACES:
    - name: eth0
      addr: 192.168.1.1/24
      description: InterfaceInterna
    - name: eth1
      addr: 200.19.0.1/24
      description: InterfaceExterna