---
hostname: iptables-firewall
ip_manage: 172.30.0.3
ssh_port: 22
username: ubuntu
password: ubuntu
device_type: linux


INTERFACES:
    - name: eth0
      addr: 10.0.0.1/24
      description: InterfaceInterna
    - name: eth1
      addr: 200.19.0.1/24
      description: InterfaceExterna
