---
hostname: cisco-firewall
ip_manage: 10.12.0.120
ssh_port: 22
username: cisco
password: cisco
device_type: cisco_ios

INTERFACES:
    - name: inside
      addr: 192.168.1.1/24
      description: InterfaceInterna
    - name: outside
      addr: 200.19.0.1/24
      description: InterfaceExterna